var settings = {
  "OnlyLive": false,
  "Command": "!roulette",
  "Permission": "Everyone",
  "PermissionInfo": "",
  "Usage": "Stream Chat",
  "MaxBet": 0,
  "MinBet": 0,
  "UseCD": false,
  "Cooldown": 0,
  "OnCooldown": "{0} the command is still on cooldown for {1} seconds!",
  "UserCooldown": 5,
  "CasterCD": true,
  "OnUserCooldown": "{0} the command is still on user cooldown for {1} seconds!",
  "BaseResponse": "{0} spins the roulette and it lands on {2} {1} ...  ",
  "NotEnoughResponse": "{0} you don't have that many {1} to gamble ",
  "WinResponse": "{0} won {1} {3} and now has {2} {3} ",
  "LoseResponse": "{0} lost {1} {3} and now has {2} {3} ",
  "TooMuchResponse": "{0} you can't gamble more than {1} {2} ",
  "TooLowResponse": "{0} you can't gamble less than {1} {2} ",
  "PermissionResp": "{0} -> only {1} ({2}) and higher can use this command",
  "InfoResponse": "To spin the roulette use !Roulette [option] [amount]. Available options to bet on: high, low, red, black, even, odd, zero, basket, dozen1-3, column1-3, any single number. For more information on the payout amounts check this link: http://imgur.com/a/uu1Yf "
};